-   id: prettier
    name: prettier
    description: ''
    entry: prettier --write --list-different --ignore-unknown
    language: node
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["prettier@2.8.4"]
    minimum_pre_commit_version: '0'
